### ISSUE TITLE
Problems with apikey

### ISSUE THREAD

**Issue by ftgo** [telefonicaid/iotagent-ul#459] opened 2020-12-23 23:31 UTC
Replicating IoT Agent tutorial (ULTRALIGHT_VERSION=1.15.0), I have provisioned the following service: 

```
curl --location --request GET 'http://localhost:4041/iot/services' \
--header 'fiware-service: openiot' \
--header 'fiware-servicepath: /'
```

result: 

```
{
    "count": 1,
    "services": [
        {
            "commands": [],
            "lazy": [],
            "attributes": [],
            "_id": "5fe3c5170b64dddf4ebf7c16",
            "resource": "iot/d",
            "apikey": "4jggokgpepnvsb2uv4s40d59ov",
            "service": "openiot",
            "subservice": "/",
            "__v": 0,
            "static_attributes": [],
            "internal_attributes": [],
            "entity_type": "Thing"
        }
    ]
}
```

However, when I send the following request it fails.

```
curl -iX POST \
  'http://localhost:7896/iot/d?k=4jggokgpepnvsb2uv4s40d59ov&i=motion001' \
  -H 'Content-Type: text/plain' \
  -H 'fiware-service: openiot' \
  -H 'fiware-servicepath: /' \
  -d 'c|1'
```

Checking [this issue](https://github.com/telefonicaid/iotagent-ul/issues/320), when I replace the `4jggokgpepnvsb2uv4s40d59ov` by `TEF`, it works properly.

**Comment by fgalan** [comment] 2021-01-07 12:34
I'm CCing @jason-fox which authored that tutorial.

Note that the issue you cite is closed... Not sure if the fix is needed in the tutorial or in the IOTA code.

**Comment by jason-fox** [comment] 2021-01-07 14:50
The default APIKey is defined in the [config.js](https://github.com/telefonicaid/iotagent-ul/blob/master/config.js#L366)

```javascript
/**
 * Default API Key, to use with device that have been provisioned without a Configuration Group.
 */
config.defaultKey = 'TEF';
```


The default API Key can be overridden by the `resource` statement when provisioning:

```console
curl -iX POST \
  'http://localhost:4041/iot/services' \
  -H 'Content-Type: application/json' \
  -H 'fiware-service: openiot' \
  -H 'fiware-servicepath: /' \
  -d '{
 "services": [
   {
     "apikey":      "4jggokgpepnvsb2uv4s40d59ov",
     "cbroker":     "http://orion:1026",
     "entity_type": "Thing",
     "resource":    "/iot/d"
   }
 ]
}'
```

The tutorials deliberately pass in an overridden key which is set up in the [docker-compose](https://github.com/FIWARE/tutorials.IoT-Agent/blob/master/docker-compose.yml#L98)

```yaml
environment:
      - "DUMMY_DEVICES_API_KEY=4jggokgpepnvsb2uv4s40d59ov"
```

The important point is that the API must match the one defined within the IoT Agent.

**Comment by ftgo** [comment] 2021-01-07 20:09
> The default APIKey is defined in the [config.js](https://github.com/telefonicaid/iotagent-ul/blob/master/config.js#L366) - the default value of `TEF` is also used within the Docker image
> 
> ```js
> /**
>  * Default API Key, to use with device that have been provisioned without a Configuration Group.
>  */
> config.defaultKey = 'TEF';
> ```
> 
> The default API Key can be overridden by the `resource` statement when provisioning (as is done in the tutorial):
> 
> ```
> curl -iX POST \
>   'http://localhost:4041/iot/services' \
>   -H 'Content-Type: application/json' \
>   -H 'fiware-service: openiot' \
>   -H 'fiware-servicepath: /' \
>   -d '{
>  "services": [
>    {
>      "apikey":      "4jggokgpepnvsb2uv4s40d59ov",
>      "cbroker":     "http://orion:1026",
>      "entity_type": "Thing",
>      "resource":    "/iot/d"
>    }
>  ]
> }'
> ```
> 
> The tutorials deliberately pass in an overridden key which is set up in the [docker-compose](https://github.com/FIWARE/tutorials.IoT-Agent/blob/master/docker-compose.yml#L98)
> 
> ```yaml
> environment:
>       - "DUMMY_DEVICES_API_KEY=4jggokgpepnvsb2uv4s40d59ov"
> ```
> 
> The important point is that the API must match the one defined within the IoT Agent.

That is exactly what I do. I provision a new service with "4jggokgpepnvsb2uv4s40d59ov" as API Key and leaved the same value within `docker-compose.yaml`, but the only value that works when sending replies from the southbound port (7896) is `TEF`.

**Comment by jason-fox** [comment] 2021-01-08 07:36
So which commands are you using to provision the device itself (along with the service group).
 
It looks likely this is an IoT Agent issue, since the problem should be reproducible with an single IoT Agent and some curl (or even a test in the Ultralight test suite.

**Comment by ftgo** [comment] 2021-01-08 10:42
I provision like this:

```
curl --silent --location --output /dev/null --request POST 'http://iot-agent:4041/iot/devices' \
--header 'Content-Type: application/json' \
--header 'fiware-service: openiot' \
--header 'fiware-servicepath: /' \
--globoff \
--data-raw '{
    "devices": [
        {
            "device_id": "device001",
            "entity_name": "urn:ngsi-ld:Device:001",
            "entity_type": "Thing",
            "protocol": "PDI-IoTA-UltraLight",
            "transport": "HTTP",
            "endpoint": "http://172.17.0.1:6001/service/v1/send",
            "commands": [
                {
                    "name": "ping",
                    "type": "command"
                }
            ],
            "attributes": [
                {
                    "name": "ping_sensor",
                    "type": "Integer"
                }
            ],
            "static_attributes": [
                {
                    "name": "refStore",
                    "type": "Relationship",
                    "value": "urn:ngsi-ld:Store:001"
                }
            ]
        }
    ]
}'
```

**Comment by jason-fox** [comment] 2021-01-08 12:34
http://localhost:7896/iot/d?k=4jggokgpepnvsb2uv4s40d59ov&i=motion001'

does not correspond with `device001`, therefore the measure is coming from an anonymous device which would take the default API Key from the config.

**Comment by ftgo** [comment] 2021-01-08 12:38
I am sorry. I have changed this while posting just to not correlate to my application specifically.

**Comment by AlvaroVega** [comment] 2021-02-02 08:36
Did you tried with latest version of iotagent? There are some recent changes about edit apikey in https://github.com/telefonicaid/iotagent-node-lib/pull/979 https://github.com/telefonicaid/iotagent-node-lib/pull/976 https://github.com/telefonicaid/iotagent-node-lib/pull/975

**Comment by ftgo** [comment] 2021-04-18 16:12
> Did you tried with latest version of iotagent? There are some recent changes about edit apikey in [telefonicaid/iotagent-node-lib#979](https://github.com/telefonicaid/iotagent-node-lib/pull/979) [telefonicaid/iotagent-node-lib#976](https://github.com/telefonicaid/iotagent-node-lib/pull/976) [telefonicaid/iotagent-node-lib#975](https://github.com/telefonicaid/iotagent-node-lib/pull/975)

@AlvaroVega I've just tried with `ORION_VERSION=3.0.0` and `ULTRALIGHT_VERSION=1.16.2` - no deal.

BTW, once it is up and running, you could test using:

**a) Runs fine and updates the corresponding attribute**
```
curl --location --request POST "http://localhost:7896/iot/d?k=TEF&i=device001" \
--header 'Content-Type: text/plain' \
--data-raw 'light_sensor|1003'
```

**b) Fails to update the corresponding attribute**
```
curl --location --request POST "http://localhost:7896/iot/d?k=4jggokgpepnvsb2uv4s40d59ov&i=device001" \
--header 'Content-Type: text/plain' \
--data-raw 'light_sensor|1005'
```

Error message:
```
{"name":"DEVICE_GROUP_NOT_FOUND","message":"Couldn\t find device group for fields: [\"resource\",\"apikey\"] and values: {\"resource\":\"/iot/d\",\"apikey\":\"4jggokgpepnvsb2uv4s40d59ov\"}"}
```

**Comment by AlvaroVega** [comment] 2021-04-19 09:01
In my case:

curl --location --request GET 'http://localhost:4061/iot/services' --header 'fiware-service: smartcity' --header 'fiware-servicepath: /'
{"count":1,"services":[{"commands":[{"name":"MiOtrocommand","type":"command","value":""}],"lazy":[],"attributes":[],"_id":"6059c2fa3ac19c577da6ed1e","resource":"/iot/d","apikey":"0pbjm5q950pfcrbs8e407ysfk","service":"smartcity","subservice":"/","description":"UL2","timestamp":true,"__v":1,"static_attributes":[],"internal_attributes":[],"entity_type":"thing"}]}[10:59]

curl -i -X GET 'http://localhost:7896/iot/d?k=0pbjm5q950pfcrbs8e407ysfk&i=dispAVG&d=c|1'  -H 'fiware-service: smartcity'   -H 'fiware-servicepath: /'  
HTTP/1.1 200 OK
X-Powered-By: Express
Content-Type: text/html; charset=utf-8
Content-Length: 0
ETag: W/"0-2jmj7l5rSw0yVb/vlWAYkK/YBwk"
Date: Mon, 19 Apr 2021 08:59:32 GMT
Connection: keep-alive
Keep-Alive: timeout=5

curl -i -X GET 'http://localhost:7896/iot/d?k=TEF&i=dispAVG&d=c|1'  -H 'fiware-service: smartcity'   -H 'fiware-servicepath: /'  
HTTP/1.1 200 OK
X-Powered-By: Express
Content-Type: text/html; charset=utf-8
Content-Length: 0
ETag: W/"0-2jmj7l5rSw0yVb/vlWAYkK/YBwk"
Date: Mon, 19 Apr 2021 08:59:47 GMT
Connection: keep-alive
Keep-Alive: timeout=5

**Comment by ftgo** [comment] 2021-04-19 12:06
```
$ curl --location --request GET 'http://localhost:4041/iot/services' --header 'fiware-service: openiot' --header 'fiware-servicepath: /'

{
    "count": 1,
    "services": [
        {
            "__v": 0,
            "_id": "607d692e86df678bac7e28f7",
            "apikey": "4jggokgpepnvsb2uv4s40d59ov",
            "attributes": [],
            "commands": [],
            "entity_type": "Thing",
            "internal_attributes": [],
            "lazy": [],
            "resource": "iot/d",
            "service": "openiot",
            "static_attributes": [],
            "subservice": "/"
        }
    ]
}
```

Based on your last answer, I've found what is wrong. We should define `resource` as `/iot/d` (starting with a slash). For some reason my service was defined without it.

Many thanks! I think we can close it.

**Comment by jason-fox** [comment] 2021-04-19 12:50
If a  provisioned `resource` path always needs a leading slash, should the [deviceGroup template](https://github.com/telefonicaid/iotagent-node-lib/blob/master/lib/templates/deviceGroup.json#L31-L35) be updated to enforce this?

```json
"resource": {
            "description": "uri for the iotagent",
            "type": "string",
            "required": true
            "pattern": "^\/.*$"
}
```

**Comment by ftgo** [comment] 2021-04-19 15:50
> If a provisioned `resource` path always needs a leading slash, should the [deviceGroup template](https://github.com/telefonicaid/iotagent-node-lib/blob/master/lib/templates/deviceGroup.json#L31-L35) be updated to enforce this?
> 
> ```json
> "resource": {
>             "description": "uri for the iotagent",
>             "type": "string",
>             "required": true,
>             "pattern": "^\/.*$"
> }
> ```

I think you are correct, it should be enforced.

**Comment by fgalan** [comment] 2021-04-19 16:09
> I think you are correct, it should be enforced.

Given this issue is now closed, maybe it is better to create a new issue about this improvement (probably the best place is https://github.com/telefonicaid/iotagent-node-lib, as this would be part of the provisioning API implemented by that library).

**Comment by ftgo** [comment] 2021-04-19 16:14
> > I think you are correct, it should be enforced.
> 
> Given this issue is now closed, maybe it is better to create a new issue about this improvement (probably the best place is https://github.com/telefonicaid/iotagent-node-lib, as this would be part of the provisioning API implemented by that library).

@fgalan I reopened the issue, in case you think it is suitable to keep fixing from here.

**Comment by fgalan** [comment] 2021-04-19 16:29
> @fgalan I reopened the issue, in case you think it is suitable to keep fixing from here.

I think is better to close this one (as it has a long history, related with the apikey issue) and create a new fresh one with a clean history in the ioagent-node-lib repository, as I suggested in my last comment.

**Closed by fgalan** 2021-04-19 16:29 UTC

**Comment by ftgo** [comment] 2021-04-24 17:50
@fgalan What is the new issue number? I would like follow up this.

**Comment by fgalan** [comment] 2021-04-26 08:37
> @fgalan What is the new issue number? I would like follow up this.

As far as I know, the issue has not been created yet, so there isn't any associated number.

Maybe @jason-fox should create it, as [proposer of the idea](https://github.com/telefonicaid/iotagent-ul/issues/459#issuecomment-822441077)?
