### ISSUE TITLE
Unable to send new measurements - Service path seems to be ignored.

### ISSUE THREAD

**Issue by dmabtrg** [telefonicaid/iotagent-ul#135] opened 2016-08-25 16:22 UTC
Hi,

after updating the docker image to the latest `develop` tag, I can no longer send measurements for the registered sensors.  Every time I try to send a new measurement, I get a `DUPLICATE_DEVICE_ID` error.

This is the device as found on the iotagentul mongo database:
```
> use iotagentul
switched to db iotagentul
> db.devices.find({'id': '0115206c51f60b48b77e4c937835795c33bb953f-kitchen-temperature'});
{
  "_id" : ObjectId("57bed55718153601004da66f"),
  "protocol" : "UL20",
  "internalId" : null,
  "subservice" : "/Franchise3",
  "service" : "tourguide",
  "name" : "0115206c51f60b48b77e4c937835795c33bb953f",
  "type" : "Restaurant",
  "id" : "0115206c51f60b48b77e4c937835795c33bb953f-kitchen-temperature",
  "creationDate" : ISODate("2016-08-25T11:24:07.277Z"),
  "subscriptions" : [ ],
  "active" : [ { "type" : "Number", "name" : "temperature:kitchen", "object_id" : "t" } ],
  "__v" : 0
}
```

This is the curl command used to send the new measurement:

```
$ curl --request POST \
       --header 'Content-Type: text/plain' \
       --header 'Fiware-Service: tourguide' \
       --header 'Fiware-ServicePath: /Franchise3' \
       --header 'X-Auth-Token: NULL' \
       --data 't|30' \
       -v \
       'http://localhost:7896/iot/d?k=tourguide-devices&i=0115206c51f60b48b77e4c937835795c33bb953f-kitchen-temperature'
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying ::1...
* Connected to localhost (::1) port 7896 (#0)
> POST /iot/d?k=tourguide-devices&i=0115206c51f60b48b77e4c937835795c33bb953f-kitchen-temperature HTTP/1.1
> Host: localhost:7896
> User-Agent: curl/7.47.0
> Accept: */*
> Content-Type: text/plain
> Fiware-Service: tourguide
> Fiware-ServicePath: /Franchise3
> X-Auth-Token: NULL
> Content-Length: 4
>
* upload completely sent off: 4 out of 4 bytes
< HTTP/1.1 409 Conflict
< X-Powered-By: Express
< Content-Type: application/json; charset=utf-8
< Content-Length: 161
< ETag: W/"a1-UREx5d5P/oxGUh+t0Y2mlw"
< Date: Thu, 25 Aug 2016 16:11:52 GMT
< Connection: keep-alive
<
* Connection #0 to host localhost left intact
{
  "name":"DUPLICATE_DEVICE_ID",
  "message":"A device with the same pair (Service, DeviceId) was found:0115206c51f60b48b77e4c937835795c33bb953f-kitchen-temperature"
}
```

An this is the log resulting log from the iot agent:

```
time=2016-08-25T16:08:13.617Z | lvl=DEBUG | corr=02b65d56-7c10-4415-85cb-a16f88e6a4f3 | trans=02b65d56-7c10-4415-85cb-a16f88e6a4f3 | op=IoTAgentNGSI.MongoDBGroupRegister | srv=tourguide | subsrv=/ | msg=Looking for entity params ["resource","apikey"] | comp=IoTAgent
time=2016-08-25T16:08:13.618Z | lvl=DEBUG | corr=02b65d56-7c10-4415-85cb-a16f88e6a4f3 | trans=02b65d56-7c10-4415-85cb-a16f88e6a4f3 | op=IoTAgentNGSI.MongoDBDeviceRegister | srv=tourguide | subsrv=/ | msg=Looking for entity with id [0115206c51f60b48b77e4c937835795c33bb953f-kitchen-temperature]. | comp=IoTAgent
time=2016-08-25T16:08:13.619Z | lvl=DEBUG | corr=02b65d56-7c10-4415-85cb-a16f88e6a4f3 | trans=02b65d56-7c10-4415-85cb-a16f88e6a4f3 | op=IoTAgentNGSI.MongoDBDeviceRegister | srv=tourguide | subsrv=/ | msg=Entity [0115206c51f60b48b77e4c937835795c33bb953f-kitchen-temperature] not found. | comp=IoTAgent
time=2016-08-25T16:08:13.619Z | lvl=DEBUG | corr=02b65d56-7c10-4415-85cb-a16f88e6a4f3 | trans=02b65d56-7c10-4415-85cb-a16f88e6a4f3 | op=IoTAgentNGSI.MongoDBDeviceRegister | srv=tourguide | subsrv=/ | msg=Looking for entity with id [0115206c51f60b48b77e4c937835795c33bb953f-kitchen-temperature]. | comp=IoTAgent
time=2016-08-25T16:08:13.619Z | lvl=DEBUG | corr=02b65d56-7c10-4415-85cb-a16f88e6a4f3 | trans=02b65d56-7c10-4415-85cb-a16f88e6a4f3 | op=IoTAgentNGSI.MongoDBDeviceRegister | srv=tourguide | subsrv=/ | msg=Entity [0115206c51f60b48b77e4c937835795c33bb953f-kitchen-temperature] not found. | comp=IoTAgent
time=2016-08-25T16:08:13.620Z | lvl=DEBUG | corr=02b65d56-7c10-4415-85cb-a16f88e6a4f3 | trans=02b65d56-7c10-4415-85cb-a16f88e6a4f3 | op=IoTAgentNGSI.MongoDBGroupRegister | srv=tourguide | subsrv=/ | msg=Looking for entity params ["service","subservice","type"] | comp=IoTAgent
time=2016-08-25T16:08:13.621Z | lvl=DEBUG | corr=02b65d56-7c10-4415-85cb-a16f88e6a4f3 | trans=02b65d56-7c10-4415-85cb-a16f88e6a4f3 | op=IoTAgentNGSI.MongoDBGroupRegister | srv=tourguide | subsrv=/ | msg=Device name not found, falling back to deviceId:type [Restaurant:0115206c51f60b48b77e4c937835795c33bb953f-kitchen-temperature] | comp=IoTAgent
time=2016-08-25T16:08:13.621Z | lvl=DEBUG | corr=02b65d56-7c10-4415-85cb-a16f88e6a4f3 | trans=02b65d56-7c10-4415-85cb-a16f88e6a4f3 | op=IoTAgentNGSI.MongoDBGroupRegister | srv=tourguide | subsrv=/ | msg=Registering device into NGSI Service:
{
    "id": "0115206c51f60b48b77e4c937835795c33bb953f-kitchen-temperature",
    "service": "tourguide",
    "subservice": "/",
    "type": "Restaurant",
    "name": "Restaurant:0115206c51f60b48b77e4c937835795c33bb953f-kitchen-temperature",
    "lazy": [],
    "active": [],
    "staticAttributes": [],
    "commands": [],
    "subscriptions": []
} | comp=IoTAgent
time=2016-08-25T16:08:13.621Z | lvl=DEBUG | corr=02b65d56-7c10-4415-85cb-a16f88e6a4f3 | trans=02b65d56-7c10-4415-85cb-a16f88e6a4f3 | op=IoTAgentNGSI.DeviceService | srv=tourguide | subsrv=/ | msg=No Context Provider registrations found for unregister | comp=IoTAgent
time=2016-08-25T16:08:13.622Z | lvl=DEBUG | corr=02b65d56-7c10-4415-85cb-a16f88e6a4f3 | trans=02b65d56-7c10-4415-85cb-a16f88e6a4f3 | op=IoTAgentNGSI.NGSIParser | srv=tourguide | subsrv=/ | msg=Initial entity created successfully. | comp=IoTAgent
time=2016-08-25T16:08:13.623Z | lvl=DEBUG | corr=02b65d56-7c10-4415-85cb-a16f88e6a4f3 | trans=02b65d56-7c10-4415-85cb-a16f88e6a4f3 | op=IoTAgentNGSI.MongoDBDeviceRegister | srv=tourguide | subsrv=/ | msg=Storing device with id [0115206c51f60b48b77e4c937835795c33bb953f-kitchen-temperature] and type [Restaurant] | comp=IoTAgent
time=2016-08-25T16:08:13.625Z | lvl=DEBUG | corr=02b65d56-7c10-4415-85cb-a16f88e6a4f3 | trans=02b65d56-7c10-4415-85cb-a16f88e6a4f3 | op=IoTAgentNGSI.MongoDBDeviceRegister | srv=tourguide | subsrv=/ | msg=Tried to insert a device with duplicate ID in the database: WriteError({"code":11000,"index":0,"errmsg":"insertDocument :: caused by :: 11000 E11000 duplicate key error index: iotagentul.devices.$id_1  dup key: { : \"0115206c51f60b48b77e4c937835795c33bb953f-kitchen-temperature\" }","op":{"subservice":"/","service":"tourguide","name":"Restaurant:0115206c51f60b48b77e4c937835795c33bb953f-kitchen-temperature","type":"Restaurant","id":"0115206c51f60b48b77e4c937835795c33bb953f-kitchen-temperature","_id":"57bf17ed18153601004da684","creationDate":"2016-08-25T16:08:13.622Z","subscriptions":[],"__v":0}}) | comp=IoTAgent
```

It seems that the servicepath/subservice is ignored and uses the default of `/`, instead of the value provided, so it fails to find the already existing device.

Thanks.

**Comment by jmcanterafonseca** [comment] 2016-08-26 07:37
@dmoranj any idea?

**Comment by dmoranj** [comment] 2016-08-29 13:35
The may be some misconception here. The `fiware-service` and `fiware-servicepath` headers are required when the Provisioning API of the IoT Agent is accessed. When you are sending measures, the Device will be uniquely identified with two pieces of information: the APIKey and the Device ID (that you are sending as query parameters).

Another important thing to take into account is that `develop` is the development branch, and, as such, it may be unstable or quickly change. I will strongly suggest you to use a fixed version.

Concerning what's happening in your setup, it seems to me that you have provisioned both the device and the device configuration with contradictory servicepaths. I would need to see you configuration and the MongoDB entity of the configuration group with APIKey `tourguide-devices`.

**Comment by dmabtrg** [comment] 2016-08-30 10:35
> The may be some misconception here. The `fiware-service` and `fiware-servicepath` headers are required when the Provisioning API of the IoT Agent is accessed. When you are sending measures, the Device will be uniquely identified with two pieces of information: the APIKey and the Device ID (that you are sending as query parameters).

Ok, no need for those headers when sending measurements.

> Another important thing to take into account is that `develop` is the development branch, and, as such, it may be unstable or quickly change. I will strongly suggest you to use a fixed version.

Yes, I know.  I tried with 1.1.7 and received a `DEVICE_GROUP_NOT_FOUND` error instead, even when using the same servicepath for both the service and the device.

> Concerning what's happening in your setup, it seems to me that you have provisioned both the device and the device configuration with contradictory servicepaths. I would need to see you configuration and the MongoDB entity of the configuration group with APIKey `tourguide-devices`.

Yes, this seems to be the problem.  The registered service uses `/` as servicepath, while the device uses `/Franchise4`.  I don't know if this behaviour has changed or if this was a bug that has been fixed, as this configuration was working for me with an older version of the agent.  Trying with both the service and the device using the same servicepath, it works.

If I understand correctly, the service and servicepath for the device must match those of the service.  Our use case for TourGuide-App is that we have several sensors in each restaurant entity, but these entities can have one of four different servicepath values (`/Franchise1` to `/Franchise4`), so in order to add those sensors to the restaurant entities, we must register those sensors using the same servicepath of the restaurant they belong to.  So now, if I've understood this, must we register a different service for each servicepath?  Is it possible to have one service for all these sensors instead of one for each servicepath?

Thanks.

**Comment by dmoranj** [comment] 2016-09-06 06:59
I'm having some trouble understanding your problem, probably due to the ambiguity of the term "service". That's 100% our fault, as the device configurations (the ones you provision in /iot/services) should have been called Configurations instead of Services to avoid conflict with the platform wide term Service (the one you use in "fiware-service").

With that said, I understand this "If I understand correctly, the service and servicepath for the device must match those of the service" really means this "If I understand correctly, the service and servicepath for the device must match those of the Configuration". And that's absolutely correct. Services and subservices are meant as a hierarchical way to isolate information between customers (or projects) so if you provision one thing in one of the subservice it won't be accesible to others.

Regarding "if I've understood this, must we register a different service for each servicepath", if it does mean "if I've understood this, must we register a different Configuration for each servicepath", once again, yes, you must do it. Multiple Configurations can be assigned to the same Servicepath but it doesn't work the opposite way.

Concerning the changes in how service and servicepaths work, we released a feature for compatibility with the old IDAS Backend, in the form of a configuration flag that puts the IoTA in Single Configuration Mode (you can see an explanation [here](https://github.com/telefonicaid/iotagent-node-lib/tree/develop#configurations-and-subservices) ).

**Comment by carloslucenah** [comment] 2016-09-06 10:36
Same problem here.

After do a service registration, the "Fiware-Service" and "Fiware-ServicePath" headers are saved in the iota database as "service" and "subservice":

`{ "_id" : ObjectId("57ce7577a37a44010083b3f9"), "subservice" : "/", "service" : "a", "type" : "thing", "apikey" : "apikey5", "resource" : "/iot/d", "staticAttributes" : [ ], "__v" : 0 }
`

When sending an observation, these headers are ignored, as it can be seen in the log:

`time=2016-09-06T07:59:02.581Z | lvl=DEBUG | corr=7151f790-0cc7-4cd2-99e7-2bae8466af6a | trans=7151f790-0cc7-4cd2-99e7-2bae8466af6a | op=IoTAgentNGSI.MongoDBGroupRegister | srv=n/a | subsrv=n/a | msg=Processing multiple HTTP measures for device [device0004] with apiKey [apikey5]
`

As you can see, service and subservice are ignored (they appear as "n/a").

The problem is that a "DEVICE_GROUP_NOT_FOUND" error arises:

`{"name":"DEVICE_GROUP_NOT_FOUND","message":"Couldn\t find device group"}`

How can service and subservice be specified at observation sending? I understood that, as in the service registration case, they should be specified with the Fiware-Service and Fiware-ServicePath headers, but they are ignored.

Thanks in advance.

**Comment by carloslucenah** [comment] 2016-09-07 10:44
Tested with https://github.com/telefonicaid/fiware-figway/tree/master/python-IDAS4/Sensors_UL20 (after changing the content-type to "text/plain"). 

Executed:
`[root@VTSS019 Sensors_UL20]# python CreateService.py bus_auto 4jggokgpepnvsb2uv4s40d59ov
* Asking to http://localhost:4041/iot/services
* Headers: {'Fiware-Service': 'bus_auto', 'content-type': 'application/json', 'Fiware-ServicePath': '/', 'X-Auth-Token': 'NULL'}
* Sending PAYLOAD:
{
    "services": [
        {
            "token": "token2",
            "apikey": "4jggokgpepnvsb2uv4s40d59ov",
            "resource": "/iot/d",
            "entity_type": "thing",
            "cbroker": "http://0.0.0.0:1026"
        }
    ]
}

...

* Status Code: 201
* Response:
{}
`

Then:

`[root@VTSS019 Sensors_UL20]# python SendObservation.py Sensor1 't|34'
* Asking to http://localhost:7896/iot/d?k=4jggokgpepnvsb2uv4s40d59ov&i=Sensor1
* Headers: {'Fiware-Service': 'bus_auto', 'content-type': 'text/plain', 'Fiware-ServicePath': '/', 'X-Auth-Token': 'NULL'}
* Sending PAYLOAD:
t|34

...

* Status Code: 404
* Response:
{"name":"DEVICE_GROUP_NOT_FOUND","message":"Couldn\t find device group"}
`

Same results.

**Comment by dmoranj** [comment] 2016-09-07 10:57
As I explained above, those headers are ignored **on purpose** in the South Bound. South Bound identification of Devices is based completely on DeviceID and APIKey. 

Regarding the use of [figway](https://github.com/telefonicaid/fiware-figway) you should be aware that that project was created for the original IDAS and I don't know if it has been kept up to date with the new IoT Agents. Contact the maintainer of that project for more information.

Considering all those factors, the problem should be with the provisioning: either the Device Groups is not provisioned, or the Device was not provisioned (a bug was fixed concerning autoprovisioning of devices for Groups that is in develop branch but not yet in master). Is difficult to diagnose the problem with just this data, but it surely does not have anything to do with the headers.

Please, try with the software in the develop branch to see if that solves your problem.

**Comment by carloslucenah** [comment] 2016-09-07 15:11
Fixed with the development version.

Thanks!

**Closed** 2016-09-12 07:37 UTC

**Comment by dmabtrg** [comment] 2016-09-21 12:52
@dmoranj, sorry for the late reply, I've been out for the las couple of weeks.  Following your advice, we've added one "configuration" (service) for each of the service-paths and that works as expected.  

Thanks.
